### ISSUE TITLE
The GUI version doesn't start on Windows 10

### ISSUE THREAD

**Issue by ZzZombo** [copperwater/xNetHack#95]
It ends instantly w/o any visible output, so no useful feedback here. The terminal version works correctly, although I didn't play much.

**Comment by entrez** [comment]
@ZzZombo: since it's been a while since you opened this issue, I wanted to let you know that this is a helpful report and hasn't been ignored.  The problem is that most (all?) of the regular xNetHack contributors are currently limited in their ability to troubleshoot this by a lack of Windows PC access.

Just for some more context for whenever it's possible to dig into this further, what version of xNetHack is this?  Is it a precompiled binary from the releases page, or did you build it yourself?

**Comment by ZzZombo** [comment]
Version 7.1.0 Windows, built May 26 2022 22:16:23, taken from the official releases page.

**Comment by copperwater** [comment]
I assume the equivalent GUI program from regular NetHack starts fine?

There's always a possibility that xNetHack 7.1 has some windowport specific bug that was fixed upstream in 3.7 after 7.1's release. I haven't touched any of the nethackW code myself.

**Comment by ZzZombo** [comment]
All NetHack executables start and play fine from version 3.4.3 up to inclusive 3.6.6. Could somebody perhaps add crash dump creation or something so that there is anything to send you? Even good old `printf` logging scattered all around the window creation code might help to pinpoint when/where it crashes.

**Comment by Gremious** [comment]
I don't know how useful this is, but I ran the app through [Debug View](https://learn.microsoft.com/en-gb/sysinternals/downloads/debugview), and this is the output

```
[22628] =================================================================
[22628] ==22628==ERROR: AddressSanitizer: access-violation on unknown address 0x000000000000 (pc 0x7ff6b12b7ddc bp 0x000000000000 sp 0x009f7f59e190 T0)
[22628] ==22628==The signal is caused by a READ memory access.
[22628] ==22628==Hint: address points to the zero page.
[22628]     #0 0x7ff6b12b7ddb in choose_windows D:\a\xNetHack\xNetHack\src\windows.c:263
[22628]     #1 0x7ff6b0d13a4e in main D:\a\xNetHack\xNetHack\sys\windows\windmain.c:537
[22628]     #2 0x7ff6b13a838f in WinMain D:\a\xNetHack\xNetHack\win\win32\NetHackW.c:241
[22628]     #3 0x7ff6b14aeca1 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:102
[22628]     #4 0x7ff6b14aebfd in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
[22628]     #5 0x7ff6b14aeabd in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
[22628]     #6 0x7ff6b14aed1d in WinMainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp:16
[22628]     #7 0x7ffa9c1026bc  (C:\Windows\System32\KERNEL32.DLL+0x1800126bc)
[22628]     #8 0x7ffa9e2edfb7  (C:\Windows\SYSTEM32\ntdll.dll+0x18005dfb7)
[22628] 
[22628] AddressSanitizer can not provide additional info.
[22628] SUMMARY: AddressSanitizer: access-violation D:\a\xNetHack\xNetHack\src\windows.c:263 in choose_windows
[22628] ==22628==ABORTING
```

So, the culprit may be something to do with https://github.com/copperwater/xNetHack/blob/7b1ce943bc5e37e4fe7e810ecb910ae827b43474/src/windows.c#L263

**Comment by copperwater** [comment]
@ZzZombo do you know if this is still happening with the current version of xNetHack? If not this can be closed

**Comment by ZzZombo** [comment]
Still an issue.

**Comment by entrez** [comment]
External report that seems to be the same: https://www.reddit.com/r/nethack/comments/1cgwwdu/xnethack_does_not_want_to_start/

**Comment by entrez** [comment]
The user behind the external report on Reddit linked above says the ASCII/non-tiles Windows executable also crashes, but after character creation (as opposed to the immediate crash on the tiles version), which may or may not be different from the original report from @ZzZombo ("I didn't play much" in the issue here, and really no specifics on Reddit about how long after character creation before it crashes).  Another Reddit user has also concurred in the same thread that he's experiencing the same thing.

**Comment by dkspence952** [comment]
Just to chime in: I can confirm exactly the same behavior on my machine. The tiles exe crashes immediately, ascii crashes immediately after asking "Is this ok?"

**Comment by copperwater** [comment]
At this point, we are close enough to the xnethack 9.0 release that this probably won't be fixed directly. I will make more of an effort to test the windows binaries before release, though that relies on me getting ahold of a windows machine which I currently don't have. If anyone wants to help out by compiling on their windows machine, let me know.
